set directory=~/.vim/backup
set backupdir=~/.vim/backup   " keep swap files here
filetype off                  " required

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree'
Plug 'airblade/vim-gitgutter'
" Plug 'neovimhaskell/haskell-vim'
" Plug 'Twinside/vim-hoogle'
Plug 'morhetz/gruvbox'
Plug 'terryma/vim-multiple-cursors'
Plug 'kien/rainbow_parentheses.vim'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'junegunn/vim-easy-align'
Plug 'ryanoasis/vim-devicons'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'wikitopian/hardmode'
Plug 'w0ng/vim-hybrid'
Plug '/usr/local/opt/fzf'
Plug 'Chiel92/vim-autoformat'
Plug 'hashivim/vim-terraform'
Plug 'vim-syntastic/syntastic'
Plug 'juliosueiras/vim-terraform-completion'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/async.vim'
Plug 'farmergreg/vim-lastplace'
" Plug 'numToStr/FTerm.nvim'
"-- Plug 'itchyny/lightline.vim'

call plug#end()              " required

" Neomake on save
" autocmd! BufWritePost * Neomake
"-- Nerdtree git plugin symbols
let g:NERDTreeGitStatusIndicatorMapCustom = {
            \ "Modified"  : "ᵐ",
            \ "Staged"    : "ˢ",
            \ "Untracked" : "ᵘ",
            \ "Renamed"   : "ʳ",
            \ "Unmerged"  : "ᶴ",
            \ "Deleted"   : "ˣ",
            \ "Dirty"     : "˜",
            \ "Clean"     : "ᵅ",
            \ "Unknown"   : "?"
            \ }

let g:NERDTreeMapOpenInTab='\r'
let g:NERDTreeHighlightCursorline=0

" Gitgutter show more signs
let g:gitgutter_max_signs = 1500

" Function for number toggle
" function! NumberToggle()
"   if(&relativenumber == 1)
"     set number
"     set norelativenumber
"   else
"     set nonumber
"     set relativenumber
"   endif
" endfunc
"
" nnoremap <C-n> :call NumberToggle()<cr>

" Function for whitespace toggle
function! WhitespaceToggle()
    set listchars=eol:¬,tab:--,trail:~,extends:>,precedes:<
    if(&list ==1)
        set nolist
    else
        set list
    endif
endfunc

nnoremap <C-t> :call WhitespaceToggle()<cr>

function! TrimWhitespace()
    let l:save_cursor = getpos('.')
    %s/\s\+$//e
    call setpos('.', l:save_cursor)
endfun

" Trim whitespace with command
command! TrimWhitespace call TrimWhitespace()
" Trim whitespace on every save
autocmd BufWritePre * :call TrimWhitespace()

" " Non-mapped function for tab toggles
" function! TabToggle()
"     if &expandtab
"         set noexpandtab
"     else
"         set expandtab
"     endif
" endfunc

" Remappings
"    Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)

"    Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

"    Disable arrows
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
"    Nerdtree
map <C-F> :NERDTreeToggle<CR>

" Other options
" let mapleader=','
" set relativenumber

" Automatic toggling between line number modes
set number

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &nu && mode() != "i" | set rnu   | endif
  autocmd BufLeave,FocusLost,InsertEnter,WinLeave   * if &nu                  | set nornu | endif
augroup END

set encoding=utf-8 " Necessary to show unicode glyphs

set backspace=2
set t_Co=256
syntax on
set termguicolors
colorscheme gruvbox
" colorscheme github_dark
set background=dark        " for the dark/light version

" " lightline
" let g:lightline = {
"   \  'colorscheme': 'gruvbox',
"   \   'active': {
"   \     'left':[ [ 'mode', 'paste' ],
"   \              [ 'gitbranch', 'readonly', 'filename', 'modified' ]
"   \     ]
"   \   },
" 	\   'component': {
" 	\     'lineinfo': ' %3l:%-2v',
" 	\   },
"   \   'component_function': {
"   \     'gitbranch': 'fugitive#head',
"   \   }
"   \ }
" let g:lightline.separator = {
" 	\   'left': '', 'right': ''
"   \}
" let g:lightline.subseparator = {
" 	\   'left': '', 'right': ''
"   \}
"
" let g:lightline.tabline = {
"   \   'left': [ ['tabs'] ],
"   \   'right': [ ['close'] ]
"   \ }
" set showtabline=2  " Show tabline
" set guioptions-=e  " Don't use GUI tabline


let g:airline_theme='term'
let g:airline_solarized_bg='dark'

" Airline
let g:airline_powerline_fonts = 1
let g:airline#extensions#syntastic#enabled = 1
let g:airline_detect_spelllang=1

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline#extensions#tabline#buffer_nr_show = 0
let g:airline#extensions#tabline#buffer_idx_mode = 0

let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = ''
let g:airline#extensions#tabline#right_sep = ''
let g:airline#extensions#tabline#right_alt_sep = ''

" We do not need to see things line -- INSERT -- anymore
set noshowmode

" unicode symbols
" let g:airline_left_sep = ''
" let g:airline_right_sep = ''

" if !exists('g:airline_symbols')
"     let g:airline_symbols = {}
" endif
" airline symbols
" let g:airline_left_sep = ''
" let g:airline_left_alt_sep = ''
" let g:airline_right_sep = ''
" let g:airline_right_alt_sep = ''
" let g:airline_symbols.branch = ''
" let g:airline_symbols.readonly = ''
" let g:airline_symbols.linenr = ''

" Close the current buffer and move to the previous one
" This replicates the idea of closing a tab
nmap <leader>bq :bp <BAR> bd #<CR>

" Move to the previous buffer
nmap <leader>p :bprevious<CR>

" Move to the next buffer
nmap <leader>n :bnext<CR>

" This replaces :tabnew which I used to bind to this mapping
nmap <leader>T :enew<cr>

" Show all open buffers and their statusl
nmap <leader>bl :ls<CR>

set shell=/bin/zsh
set laststatus=2
set cursorline

" transparwent background
highlight Normal term=NONE cterm=NONE ctermbg=NONE ctermfg=NONE gui=NONE guibg=NONE
" highlight Comment term=bold cterm=bold ctermbg=NONE ctermfg=NONE gui=NONE guibg=NONE

" highlight Cursor ctermfg=White ctermbg=Yellow cterm=bold guifg=white guibg=yellow gui=bold
" highlight lineNr term=bold cterm=none ctermbg=none ctermfg=none gui=bold
" highlight CursorLine term=bold cterm=none ctermbg=none ctermfg=none gui=bold
" highlight CursorLineNr term=bold cterm=none ctermbg=none ctermfg=yellow gui=bold


set splitbelow
set tabstop=4
set shiftwidth=4
set expandtab
set encoding=utf8

filetype plugin indent on

" Remember cursor position
augroup vimrc-remember-cursor-position
    autocmd!
    autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g`\"" | endif
augroup END

" set nospell
set smartindent
